# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'course.ui'
#
# Created: Mon May  1 22:59:32 2017
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(773, 480)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 751, 131))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.adsoyad = QtGui.QLineEdit(self.groupBox)
        self.adsoyad.setGeometry(QtCore.QRect(90, 20, 151, 20))
        self.adsoyad.setObjectName(_fromUtf8("adsoyad"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 47, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.adres = QtGui.QTextEdit(self.groupBox)
        self.adres.setGeometry(QtCore.QRect(90, 50, 151, 71))
        self.adres.setObjectName(_fromUtf8("adres"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(260, 20, 47, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.telefon = QtGui.QLineEdit(self.groupBox)
        self.telefon.setGeometry(QtCore.QRect(320, 20, 113, 20))
        self.telefon.setObjectName(_fromUtf8("telefon"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(260, 50, 47, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.meslek = QtGui.QLineEdit(self.groupBox)
        self.meslek.setGeometry(QtCore.QRect(320, 50, 113, 20))
        self.meslek.setObjectName(_fromUtf8("meslek"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(450, 20, 47, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.ucret = QtGui.QLineEdit(self.groupBox)
        self.ucret.setGeometry(QtCore.QRect(500, 20, 61, 20))
        self.ucret.setObjectName(_fromUtf8("ucret"))
        self.kayitTarihi = QtGui.QDateEdit(self.groupBox)
        self.kayitTarihi.setGeometry(QtCore.QRect(500, 50, 110, 22))
        self.kayitTarihi.setDate(QtCore.QDate(2017, 1, 1))
        self.kayitTarihi.setObjectName(_fromUtf8("kayitTarihi"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(440, 50, 61, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(260, 70, 481, 51))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.checkBox_6 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_6.setGeometry(QtCore.QRect(330, 20, 71, 17))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_2.setGeometry(QtCore.QRect(100, 20, 39, 17))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_5 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_5.setGeometry(QtCore.QRect(280, 20, 50, 17))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox.setGeometry(QtCore.QRect(30, 20, 67, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_3.setGeometry(QtCore.QRect(140, 20, 71, 17))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_7 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_7.setGeometry(QtCore.QRect(400, 20, 50, 17))
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.checkBox_4 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_4.setGeometry(QtCore.QRect(210, 20, 70, 17))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.email = QtGui.QLineEdit(self.groupBox)
        self.email.setGeometry(QtCore.QRect(590, 20, 151, 20))
        self.email.setInputMask(_fromUtf8(""))
        self.email.setText(_fromUtf8(""))
        self.email.setObjectName(_fromUtf8("email"))
        self.radioAktif = QtGui.QRadioButton(self.groupBox)
        self.radioAktif.setGeometry(QtCore.QRect(630, 50, 82, 17))
        self.radioAktif.setChecked(True)
        self.radioAktif.setObjectName(_fromUtf8("radioAktif"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 751, 281))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.aylikDersTakibi = QtGui.QCalendarWidget(self.groupBox_2)
        self.aylikDersTakibi.setEnabled(True)
        self.aylikDersTakibi.setGeometry(QtCore.QRect(10, 20, 264, 183))
        self.aylikDersTakibi.setAcceptDrops(False)
        self.aylikDersTakibi.setGridVisible(False)
        self.aylikDersTakibi.setSelectionMode(QtGui.QCalendarWidget.SingleSelection)
        self.aylikDersTakibi.setObjectName(_fromUtf8("aylikDersTakibi"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(280, 20, 451, 181))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.kacsaat = QtGui.QSpinBox(self.groupBox_4)
        self.kacsaat.setGeometry(QtCore.QRect(90, 20, 42, 22))
        self.kacsaat.setObjectName(_fromUtf8("kacsaat"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(150, 20, 47, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(150, 70, 47, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.timeBaslangic = QtGui.QTimeEdit(self.groupBox_4)
        self.timeBaslangic.setGeometry(QtCore.QRect(210, 20, 118, 22))
        self.timeBaslangic.setTime(QtCore.QTime(8, 0, 0))
        self.timeBaslangic.setCalendarPopup(False)
        self.timeBaslangic.setObjectName(_fromUtf8("timeBaslangic"))
        self.timeBitis = QtGui.QTimeEdit(self.groupBox_4)
        self.timeBitis.setGeometry(QtCore.QRect(210, 60, 118, 22))
        self.timeBitis.setTime(QtCore.QTime(8, 0, 0))
        self.timeBitis.setObjectName(_fromUtf8("timeBitis"))
        self.bitisTarihi = QtGui.QDateEdit(self.groupBox_4)
        self.bitisTarihi.setGeometry(QtCore.QRect(210, 110, 121, 22))
        self.bitisTarihi.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 1, 1), QtCore.QTime(0, 0, 0)))
        self.bitisTarihi.setCalendarPopup(False)
        self.bitisTarihi.setObjectName(_fromUtf8("bitisTarihi"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(150, 120, 46, 13))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.pushVazgec = QtGui.QPushButton(self.groupBox_2)
        self.pushVazgec.setGeometry(QtCore.QRect(660, 230, 75, 23))
        self.pushVazgec.setObjectName(_fromUtf8("pushVazgec"))
        self.pushKaydet = QtGui.QPushButton(self.groupBox_2)
        self.pushKaydet.setGeometry(QtCore.QRect(580, 230, 75, 23))
        self.pushKaydet.setObjectName(_fromUtf8("pushKaydet"))
        self.pushButton = QtGui.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 240, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 240, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 240, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 773, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDosya = QtGui.QMenu(self.menubar)
        self.menuDosya.setObjectName(_fromUtf8("menuDosya"))
        self.menuHakk_nda = QtGui.QMenu(self.menubar)
        self.menuHakk_nda.setObjectName(_fromUtf8("menuHakk_nda"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionYedek_Al = QtGui.QAction(MainWindow)
        self.actionYedek_Al.setObjectName(_fromUtf8("actionYedek_Al"))
        self.actionYaz_c_ya_G_nder = QtGui.QAction(MainWindow)
        self.actionYaz_c_ya_G_nder.setObjectName(_fromUtf8("actionYaz_c_ya_G_nder"))
        self.actionMail_At = QtGui.QAction(MainWindow)
        self.actionMail_At.setObjectName(_fromUtf8("actionMail_At"))
        self.actionGenel_Bilgi = QtGui.QAction(MainWindow)
        self.actionGenel_Bilgi.setObjectName(_fromUtf8("actionGenel_Bilgi"))
        self.actionKullan_m_D_k_man = QtGui.QAction(MainWindow)
        self.actionKullan_m_D_k_man.setObjectName(_fromUtf8("actionKullan_m_D_k_man"))
        self.actionVeritan_S_f_rla = QtGui.QAction(MainWindow)
        self.actionVeritan_S_f_rla.setObjectName(_fromUtf8("actionVeritan_S_f_rla"))
        self.menuDosya.addAction(self.actionYedek_Al)
        self.menuDosya.addAction(self.actionYaz_c_ya_G_nder)
        self.menuDosya.addAction(self.actionMail_At)
        self.menuHakk_nda.addAction(self.actionGenel_Bilgi)
        self.menuHakk_nda.addAction(self.actionKullan_m_D_k_man)
        self.menuHakk_nda.addAction(self.actionVeritan_S_f_rla)
        self.menubar.addAction(self.menuDosya.menuAction())
        self.menubar.addAction(self.menuHakk_nda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionYedek_Al, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.yedekAl)
        QtCore.QObject.connect(self.actionYaz_c_ya_G_nder, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.yaziciyaGonder)
        QtCore.QObject.connect(self.actionMail_At, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.mailGonder)
        QtCore.QObject.connect(self.actionGenel_Bilgi, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.kullanimBilgisi)
        QtCore.QObject.connect(self.actionVeritan_S_f_rla, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.veritabaniSifirla)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Follow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Kişisel Bilgiler", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Ad Soyad", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Adres", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Telefon", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Meslek", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Ücret", None, QtGui.QApplication.UnicodeUTF8))
        self.ucret.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "TL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Kayıt Tarihi", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Ders Günleri", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("MainWindow", "Cumartesi", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("MainWindow", "Salı", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("MainWindow", "Cuma", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Pazartesi", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("MainWindow", "Çarşamba", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("MainWindow", "Pazar", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("MainWindow", "Perşembe", None, QtGui.QApplication.UnicodeUTF8))
        self.email.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "e-mail ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioAktif.setText(QtGui.QApplication.translate("MainWindow", "Aktif", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Aylık Ders Takibi", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Saat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Kaç Saat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Başlangiç", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Bitiş", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Bitiş Tarihi", None, QtGui.QApplication.UnicodeUTF8))
        self.pushVazgec.setText(QtGui.QApplication.translate("MainWindow", "Vazgeç", None, QtGui.QApplication.UnicodeUTF8))
        self.pushKaydet.setText(QtGui.QApplication.translate("MainWindow", "Kaydet", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Ara", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Güncelle", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Listele", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDosya.setTitle(QtGui.QApplication.translate("MainWindow", "Dosya", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHakk_nda.setTitle(QtGui.QApplication.translate("MainWindow", "Hakkında", None, QtGui.QApplication.UnicodeUTF8))
        self.actionYedek_Al.setText(QtGui.QApplication.translate("MainWindow", "Yedek Al", None, QtGui.QApplication.UnicodeUTF8))
        self.actionYaz_c_ya_G_nder.setText(QtGui.QApplication.translate("MainWindow", "Yazıcıya Gönder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMail_At.setText(QtGui.QApplication.translate("MainWindow", "Mail Gönder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenel_Bilgi.setText(QtGui.QApplication.translate("MainWindow", "Genel Bilgi", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKullan_m_D_k_man.setText(QtGui.QApplication.translate("MainWindow", "Kullanım Dökümanı", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVeritan_S_f_rla.setText(QtGui.QApplication.translate("MainWindow", "Veritanı Sıfırla", None, QtGui.QApplication.UnicodeUTF8))

